#!/usr/bin/env python3
"""
Splits the generator palette's nouns into the slot types a story skeleton needs.

The skeletons have blanks. The CODE fills those blanks, not the model, so an
off-level or unsafe noun is impossible before generation starts rather than
being caught afterwards. That needs to know which palette nouns are creatures,
which are objects and which are places.

Emits ../content/slot-vocab.json mapping word -> earliest stage it is available.
Fails the build if any word here is not actually in the palette.
"""
import json, sys
from pathlib import Path

CREATURE = """
bug cat cub dog pug pup duck fox hen hog rat yak chick fish moth crab frog
skunk slug crane mice mole mule snake bird bee bunny crow deer goat puppy seal
sheep snail toad cow hawk mouse owl trout chicken chipmunk dolphin hamster
kitten lizard rabbit robin tiger turtle
"""

# Things a five-year-old could pick up and carry. A skeleton where an object
# goes missing and turns up somewhere else needs one of these - "Sam puts a bed
# somewhere safe" is a different story from the one the skeleton is telling.
PORTABLE = """
fan map mat pad pan pin tin
bag cup fig gum mug net nut pen pod pot top
bell box doll hat jam jug lid rag rock rug sack sock tack wig yam
dish ring shell
branch brick clock dress drum flag fudge lunch match milk nest sled snack stick
twig
bike blade bone cake cane cape cone cube flute globe kite note pipe plate pole
rice robe rope rose skate spike stone tape tile tube grape
card cart chart cork corn fern fork hammer horn jar ladder letter shirt skirt
supper thorn
bean bowl candy chain clay coat cream hay jelly leaf mail meal nail pail peach
penny pie seed sheet soap tie toast tray wheel
book broom coin crown food gear hood hook oil spear spoon straw toy wool
apple backpack basket blanket blossom bottle bubble butter button cage candle
carrot cupcake flashlight football handle helmet ice kettle knot lantern magnet
mitten muffin napkin orange page pancake paper pebble pencil phone photo pumpkin
puppet ribbon robot rocket wagon
"""

# Too big, too fixed, or part of the scenery. Fine to stand next to, wrong to
# carry off.
FIXTURE = """
bed bus cot tub
jet log van web
stump trunk bench shelf
plane slide stove vine
car harp
boat jeep oak seat train tree
chair root stair
bathtub campfire fence mailbox pocket table window
"""

PLACE = """
pit
den
hill hut lab mill
bath path shed shop
bank bridge grass patch pond sand
cave hive hole home lake slope gate
barn corner farm fort park port shore store yard
beach road sea sky stream street trail
brook ground house lawn pool roof room town wood zoo
anthill bedroom cabin castle city doghouse field garden hilltop jungle
playground puddle sandbox treehouse tunnel village
"""

# Palette words that name a human and should never have been in there. The
# content validator blocks HUMAN_NOUNS, but these were not on that list, so a
# chapter could legally have introduced a king or a vet. Flagged, not silently
# dropped, so the palette itself gets fixed.
HUMANS_FOUND_IN_PALETTE = "vet king queen clown twin".split()


def words(blob: str) -> list[str]:
    return blob.split()


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    stages = json.loads((root / "content" / "stages.json").read_text())

    # earliest stage each palette noun becomes available
    earliest: dict[str, int] = {}
    for s in stages["stages"]:
        for w in s["generator_palette"]["nouns"]:
            earliest.setdefault(w, s["id"])

    problems = []
    for w in HUMANS_FOUND_IN_PALETTE:
        if w in earliest:
            problems.append(
                f"'{w}' is a human and is in the stage {earliest[w]} palette. "
                f"Remove it from palettes.py and add it to HUMAN_NOUNS."
            )

    out: dict[str, dict[str, int]] = {}
    seen: dict[str, str] = {}
    for kind, blob in (
        ("creature", CREATURE), ("portable", PORTABLE),
        ("fixture", FIXTURE), ("place", PLACE),
    ):
        out[kind] = {}
        for w in words(blob):
            if w not in earliest:
                problems.append(f"'{w}' is classified as {kind} but is not in any palette")
                continue
            if w in seen:
                problems.append(f"'{w}' classified as both {seen[w]} and {kind}")
                continue
            seen[w] = kind
            out[kind][w] = earliest[w]

    # 'object' is the union. Skeletons that genuinely do not care whether the
    # thing can be carried use this and get the widest choice.
    out["object"] = {**out["portable"], **out["fixture"]}

    if problems:
        print(f"BUILD FAILED - {len(problems)} problem(s)")
        for p in problems:
            print("  " + p)
        return 1

    doc = {
        "_readme": (
            "word -> earliest stage it may be used. Generated by "
            "tools/build_slot_vocab.py from the generator palette in stages.json. "
            "Do not hand-edit."
        ),
        "slots": out,
    }
    (root / "content" / "slot-vocab.json").write_text(json.dumps(doc, indent=2))

    print("Wrote content/slot-vocab.json")
    for kind in out:
        by_stage = [sum(1 for v in out[kind].values() if v <= s) for s in range(1, 11)]
        print(f"  {kind:9s} total {len(out[kind]):4d}   available by stage: {by_stage}")

    thin = [
        (kind, s)
        for kind in out
        for s in range(1, 11)
        if sum(1 for v in out[kind].values() if v <= s) < 3
    ]
    if thin:
        print("\nThin slots (fewer than 3 choices, so stories will repeat):")
        for kind, s in thin:
            print(f"  {kind} at stage {s}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
