/* AUTO-GENERATED reference data — see docs/STORY_IMAGE_SYSTEM.md for how this
 * manifest was built (grid detection + per-panel visual inspection, 2026-08-21).
 * Do not hand-edit entries without re-inspecting the corresponding image. */

import type { Chapter } from './chapters.ts';

export type SceneEnvironment =
  | 'beach'
  | 'countryside'
  | 'desert'
  | 'fantasy'
  | 'farm'
  | 'forest'
  | 'indoor-home'
  | 'indoor-kitchen'
  | 'indoor-library'
  | 'jungle'
  | 'meadow'
  | 'mountain'
  | 'ocean'
  | 'outdoor-field'
  | 'sky'
  | 'snow'
  | 'space'
  | 'train-station'
  | 'underwater'
  | 'urban';

export type SceneCharacters =
  | 'boy-girl'
  | 'none'
  | 'pair-boy-dog'
  | 'pair-girl-dog'
  | 'solo-boy'
  | 'solo-girl'
  | 'trio';

export interface SceneAsset {
  id: string;
  src: string;
  width: number;
  height: number;
  sourceFile: string;
  sourcePanel: string;
  theme: string[];
  environment: SceneEnvironment;
  indoor: boolean;
  timeOfDay: 'day' | 'dusk' | 'night';
  weatherSeason: string | null;
  fantasy: boolean;
  characters: SceneCharacters;
  characterCount: number;
  dogPresent: boolean;
  otherAnimals: string[];
  transportation: string[];
  activity: string;
  emotionalTone: string;
  keywords: string[];
  ambience: Chapter['ambience'][];
  focal: { x: number; y: number };
}

export const SCENE_MANIFEST: SceneAsset[] = [
  {
    id: 'solo-girl-beach-sunset-01',
    src: '/images/scenes/solo-girl-beach-sunset-01.jpg',
    width: 324,
    height: 260,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_24_53 AM.png',
    sourcePanel: 'r1c1',
    theme: ['ocean', 'beach'],
    environment: 'beach',
    indoor: false,
    timeOfDay: 'dusk',
    weatherSeason: null,
    fantasy: false,
    characters: 'solo-girl',
    characterCount: 1,
    dogPresent: false,
    otherAnimals: [],
    transportation: [],
    activity: 'watching the sunset over the waves',
    emotionalTone: 'calm',
    keywords: ['ocean', 'beach', 'sunset', 'waves', 'shore'],
    ambience: ['ocean'],
    focal: { x: 0.3, y: 0.6 },
  },
  {
    id: 'solo-boy-mountain-overlook-01',
    src: '/images/scenes/solo-boy-mountain-overlook-01.jpg',
    width: 333,
    height: 260,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_24_53 AM.png',
    sourcePanel: 'r1c2',
    theme: ['mountains', 'adventure'],
    environment: 'mountain',
    indoor: false,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: false,
    characters: 'solo-boy',
    characterCount: 1,
    dogPresent: false,
    otherAnimals: [],
    transportation: [],
    activity: 'looking out over a mountain valley',
    emotionalTone: 'adventurous',
    keywords: ['mountain', 'valley', 'river', 'hiking', 'overlook'],
    ambience: ['countryside', 'fantasy'],
    focal: { x: 0.35, y: 0.55 },
  },
  {
    id: 'solo-girl-meadow-firefly-jar-01',
    src: '/images/scenes/solo-girl-meadow-firefly-jar-01.jpg',
    width: 348,
    height: 260,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_24_53 AM.png',
    sourcePanel: 'r1c3',
    theme: ['meadow', 'forest'],
    environment: 'meadow',
    indoor: false,
    timeOfDay: 'dusk',
    weatherSeason: null,
    fantasy: true,
    characters: 'solo-girl',
    characterCount: 1,
    dogPresent: false,
    otherAnimals: [],
    transportation: [],
    activity: 'holding a glowing jar in a flower meadow',
    emotionalTone: 'wonder',
    keywords: ['meadow', 'flowers', 'forest', 'glow', 'jar', 'firefly'],
    ambience: ['fantasy', 'countryside'],
    focal: { x: 0.35, y: 0.6 },
  },
  {
    id: 'solo-boy-bedroom-window-night-01',
    src: '/images/scenes/solo-boy-bedroom-window-night-01.jpg',
    width: 359,
    height: 260,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_24_53 AM.png',
    sourcePanel: 'r1c4',
    theme: ['bedroom', 'night sky'],
    environment: 'indoor-home',
    indoor: true,
    timeOfDay: 'night',
    weatherSeason: null,
    fantasy: false,
    characters: 'solo-boy',
    characterCount: 1,
    dogPresent: false,
    otherAnimals: [],
    transportation: [],
    activity: 'looking out the window at the moon before bed',
    emotionalTone: 'cozy',
    keywords: ['bedroom', 'night', 'moon', 'stars', 'window', 'bedtime'],
    ambience: ['fantasy', 'space'],
    focal: { x: 0.4, y: 0.55 },
  },
  {
    id: 'solo-girl-fantasy-castle-rainbow-01',
    src: '/images/scenes/solo-girl-fantasy-castle-rainbow-01.jpg',
    width: 324,
    height: 231,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_24_53 AM.png',
    sourcePanel: 'r2c1',
    theme: ['fantasy castle', 'rainbow'],
    environment: 'fantasy',
    indoor: false,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: true,
    characters: 'solo-girl',
    characterCount: 1,
    dogPresent: false,
    otherAnimals: [],
    transportation: [],
    activity: 'discovering a fairytale castle across the valley',
    emotionalTone: 'wonder',
    keywords: ['castle', 'fantasy', 'rainbow', 'waterfall', 'cliff'],
    ambience: ['fantasy'],
    focal: { x: 0.3, y: 0.5 },
  },
  {
    id: 'solo-boy-enchanted-forest-sword-01',
    src: '/images/scenes/solo-boy-enchanted-forest-sword-01.jpg',
    width: 333,
    height: 231,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_24_53 AM.png',
    sourcePanel: 'r2c2',
    theme: ['enchanted forest', 'adventure'],
    environment: 'forest',
    indoor: false,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: true,
    characters: 'solo-boy',
    characterCount: 1,
    dogPresent: false,
    otherAnimals: [],
    transportation: [],
    activity: 'holding up a toy sword in a magical forest',
    emotionalTone: 'adventurous',
    keywords: ['forest', 'sword', 'cape', 'adventure', 'enchanted'],
    ambience: ['fantasy', 'jungle'],
    focal: { x: 0.4, y: 0.55 },
  },
  {
    id: 'solo-girl-forest-bridge-cottage-01',
    src: '/images/scenes/solo-girl-forest-bridge-cottage-01.jpg',
    width: 348,
    height: 231,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_24_53 AM.png',
    sourcePanel: 'r2c3',
    theme: ['forest', 'cottage'],
    environment: 'forest',
    indoor: false,
    timeOfDay: 'dusk',
    weatherSeason: null,
    fantasy: false,
    characters: 'solo-girl',
    characterCount: 1,
    dogPresent: false,
    otherAnimals: [],
    transportation: [],
    activity: 'sitting by a stone bridge near a cottage',
    emotionalTone: 'calm',
    keywords: ['forest', 'bridge', 'pond', 'cottage', 'lily pads'],
    ambience: ['countryside', 'fantasy'],
    focal: { x: 0.35, y: 0.6 },
  },
  {
    id: 'solo-boy-desert-canyon-sunset-01',
    src: '/images/scenes/solo-boy-desert-canyon-sunset-01.jpg',
    width: 359,
    height: 231,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_24_53 AM.png',
    sourcePanel: 'r2c4',
    theme: ['desert', 'canyon'],
    environment: 'desert',
    indoor: false,
    timeOfDay: 'dusk',
    weatherSeason: null,
    fantasy: false,
    characters: 'solo-boy',
    characterCount: 1,
    dogPresent: false,
    otherAnimals: [],
    transportation: [],
    activity: 'looking out over desert canyons at sunset',
    emotionalTone: 'adventurous',
    keywords: ['desert', 'canyon', 'cactus', 'sunset', 'mesa'],
    ambience: ['countryside'],
    focal: { x: 0.35, y: 0.55 },
  },
  {
    id: 'solo-boy-farm-fence-sunset-01',
    src: '/images/scenes/solo-boy-farm-fence-sunset-01.jpg',
    width: 324,
    height: 208,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_24_53 AM.png',
    sourcePanel: 'r3c1',
    theme: ['farm', 'countryside'],
    environment: 'farm',
    indoor: false,
    timeOfDay: 'dusk',
    weatherSeason: null,
    fantasy: false,
    characters: 'solo-boy',
    characterCount: 1,
    dogPresent: false,
    otherAnimals: [],
    transportation: [],
    activity: 'sitting on a fence watching the farm at sunset',
    emotionalTone: 'calm',
    keywords: ['farm', 'fence', 'windmill', 'sunset', 'countryside'],
    ambience: ['farm', 'countryside'],
    focal: { x: 0.3, y: 0.55 },
  },
  {
    id: 'solo-girl-rain-umbrella-night-01',
    src: '/images/scenes/solo-girl-rain-umbrella-night-01.jpg',
    width: 333,
    height: 208,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_24_53 AM.png',
    sourcePanel: 'r3c2',
    theme: ['rain', 'city street'],
    environment: 'urban',
    indoor: false,
    timeOfDay: 'night',
    weatherSeason: 'rain',
    fantasy: false,
    characters: 'solo-girl',
    characterCount: 1,
    dogPresent: false,
    otherAnimals: [],
    transportation: [],
    activity: 'jumping in puddles with an umbrella in the rain',
    emotionalTone: 'joyful',
    keywords: ['rain', 'umbrella', 'puddle', 'night', 'street'],
    ambience: ['countryside'],
    focal: { x: 0.4, y: 0.6 },
  },
  {
    id: 'solo-boy-jungle-temple-ruins-01',
    src: '/images/scenes/solo-boy-jungle-temple-ruins-01.jpg',
    width: 348,
    height: 208,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_24_53 AM.png',
    sourcePanel: 'r3c3',
    theme: ['jungle', 'ancient ruins'],
    environment: 'jungle',
    indoor: false,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: false,
    characters: 'solo-boy',
    characterCount: 1,
    dogPresent: false,
    otherAnimals: [],
    transportation: [],
    activity: 'exploring ancient temple ruins in the jungle',
    emotionalTone: 'adventurous',
    keywords: ['jungle', 'temple', 'ruins', 'explorer', 'stairs'],
    ambience: ['jungle'],
    focal: { x: 0.4, y: 0.6 },
  },
  {
    id: 'solo-girl-underwater-turtle-01',
    src: '/images/scenes/solo-girl-underwater-turtle-01.jpg',
    width: 359,
    height: 208,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_24_53 AM.png',
    sourcePanel: 'r3c4',
    theme: ['underwater', 'ocean'],
    environment: 'underwater',
    indoor: false,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: false,
    characters: 'solo-girl',
    characterCount: 1,
    dogPresent: false,
    otherAnimals: ['turtle', 'fish'],
    transportation: [],
    activity: 'swimming underwater with a sea turtle',
    emotionalTone: 'wonder',
    keywords: ['underwater', 'ocean', 'turtle', 'coral', 'swimming', 'fish'],
    ambience: ['ocean'],
    focal: { x: 0.35, y: 0.55 },
  },
  {
    id: 'solo-boy-camping-telescope-night-01',
    src: '/images/scenes/solo-boy-camping-telescope-night-01.jpg',
    width: 324,
    height: 194,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_24_53 AM.png',
    sourcePanel: 'r4c1',
    theme: ['camping', 'stars'],
    environment: 'forest',
    indoor: false,
    timeOfDay: 'night',
    weatherSeason: null,
    fantasy: false,
    characters: 'solo-boy',
    characterCount: 1,
    dogPresent: false,
    otherAnimals: [],
    transportation: [],
    activity: 'looking through a telescope at the night sky while camping',
    emotionalTone: 'wonder',
    keywords: ['camping', 'telescope', 'stars', 'tent', 'night sky'],
    ambience: ['space', 'countryside'],
    focal: { x: 0.3, y: 0.55 },
  },
  {
    id: 'solo-girl-ballet-bedroom-01',
    src: '/images/scenes/solo-girl-ballet-bedroom-01.jpg',
    width: 333,
    height: 194,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_24_53 AM.png',
    sourcePanel: 'r4c2',
    theme: ['ballet', 'bedroom'],
    environment: 'indoor-home',
    indoor: true,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: false,
    characters: 'solo-girl',
    characterCount: 1,
    dogPresent: false,
    otherAnimals: [],
    transportation: [],
    activity: 'dancing ballet in a sunlit bedroom',
    emotionalTone: 'joyful',
    keywords: ['ballet', 'dance', 'bedroom', 'tutu', 'dancing'],
    ambience: [],
    focal: { x: 0.4, y: 0.55 },
  },
  {
    id: 'solo-boy-soccer-field-sunset-01',
    src: '/images/scenes/solo-boy-soccer-field-sunset-01.jpg',
    width: 348,
    height: 194,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_24_53 AM.png',
    sourcePanel: 'r4c3',
    theme: ['soccer', 'sports'],
    environment: 'outdoor-field',
    indoor: false,
    timeOfDay: 'dusk',
    weatherSeason: null,
    fantasy: false,
    characters: 'solo-boy',
    characterCount: 1,
    dogPresent: false,
    otherAnimals: [],
    transportation: [],
    activity: 'holding a soccer ball on the field at sunset',
    emotionalTone: 'joyful',
    keywords: ['soccer', 'sports', 'field', 'ball', 'game'],
    ambience: ['countryside'],
    focal: { x: 0.3, y: 0.55 },
  },
  {
    id: 'solo-girl-aurora-snow-night-01',
    src: '/images/scenes/solo-girl-aurora-snow-night-01.jpg',
    width: 359,
    height: 194,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_24_53 AM.png',
    sourcePanel: 'r4c4',
    theme: ['aurora', 'snow'],
    environment: 'snow',
    indoor: false,
    timeOfDay: 'night',
    weatherSeason: 'snow',
    fantasy: false,
    characters: 'solo-girl',
    characterCount: 1,
    dogPresent: false,
    otherAnimals: [],
    transportation: [],
    activity: 'watching the aurora over a snowy forest',
    emotionalTone: 'wonder',
    keywords: ['aurora', 'northern lights', 'snow', 'night', 'winter'],
    ambience: ['space', 'fantasy'],
    focal: { x: 0.35, y: 0.55 },
  },
  {
    id: 'solo-girl-cardboard-plane-clouds-01',
    src: '/images/scenes/solo-girl-cardboard-plane-clouds-01.jpg',
    width: 324,
    height: 185,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_24_53 AM.png',
    sourcePanel: 'r5c1',
    theme: ['imaginative play', 'sky'],
    environment: 'sky',
    indoor: false,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: true,
    characters: 'solo-girl',
    characterCount: 1,
    dogPresent: false,
    otherAnimals: [],
    transportation: ['airplane'],
    activity: 'flying a pretend cardboard-box airplane through the clouds',
    emotionalTone: 'joyful',
    keywords: ['airplane', 'imagination', 'clouds', 'hot air balloon', 'flying', 'pretend'],
    ambience: ['space', 'fantasy'],
    focal: { x: 0.4, y: 0.5 },
  },
  {
    id: 'solo-boy-library-reading-01',
    src: '/images/scenes/solo-boy-library-reading-01.jpg',
    width: 333,
    height: 185,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_24_53 AM.png',
    sourcePanel: 'r5c2',
    theme: ['library', 'reading'],
    environment: 'indoor-library',
    indoor: true,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: false,
    characters: 'solo-boy',
    characterCount: 1,
    dogPresent: false,
    otherAnimals: [],
    transportation: [],
    activity: 'reading a book in a cozy library',
    emotionalTone: 'calm',
    keywords: ['library', 'books', 'reading', 'indoor', 'quiet'],
    ambience: [],
    focal: { x: 0.4, y: 0.55 },
  },
  {
    id: 'solo-girl-kitchen-baking-01',
    src: '/images/scenes/solo-girl-kitchen-baking-01.jpg',
    width: 348,
    height: 185,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_24_53 AM.png',
    sourcePanel: 'r5c3',
    theme: ['baking', 'kitchen'],
    environment: 'indoor-kitchen',
    indoor: true,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: false,
    characters: 'solo-girl',
    characterCount: 1,
    dogPresent: false,
    otherAnimals: [],
    transportation: [],
    activity: 'baking and decorating a cake in the kitchen',
    emotionalTone: 'joyful',
    keywords: ['baking', 'cake', 'kitchen', 'cooking', 'chef'],
    ambience: [],
    focal: { x: 0.4, y: 0.55 },
  },
  {
    id: 'solo-boy-train-station-wave-01',
    src: '/images/scenes/solo-boy-train-station-wave-01.jpg',
    width: 359,
    height: 185,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_24_53 AM.png',
    sourcePanel: 'r5c4',
    theme: ['train', 'station'],
    environment: 'train-station',
    indoor: false,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: false,
    characters: 'solo-boy',
    characterCount: 1,
    dogPresent: false,
    otherAnimals: [],
    transportation: ['train'],
    activity: 'waving at a steam train pulling into the station',
    emotionalTone: 'joyful',
    keywords: ['train', 'station', 'steam engine', 'platform', 'wave'],
    ambience: ['countryside'],
    focal: { x: 0.35, y: 0.55 },
  },
  {
    id: 'trio-forest-waterfall-overlook-01',
    src: '/images/scenes/trio-forest-waterfall-overlook-01.jpg',
    width: 344,
    height: 298,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_03 AM.png',
    sourcePanel: 'r1c1',
    theme: ['forest', 'waterfall'],
    environment: 'forest',
    indoor: false,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: false,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: [],
    transportation: [],
    activity: 'sitting together looking out over a forest waterfall',
    emotionalTone: 'calm',
    keywords: ['forest', 'waterfall', 'overlook', 'valley'],
    ambience: ['jungle', 'countryside'],
    focal: { x: 0.3, y: 0.6 },
  },
  {
    id: 'trio-lighthouse-cliff-sunset-01',
    src: '/images/scenes/trio-lighthouse-cliff-sunset-01.jpg',
    width: 345,
    height: 298,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_03 AM.png',
    sourcePanel: 'r1c2',
    theme: ['ocean', 'lighthouse'],
    environment: 'ocean',
    indoor: false,
    timeOfDay: 'dusk',
    weatherSeason: null,
    fantasy: false,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: [],
    transportation: ['sailboat'],
    activity: 'sitting on a cliff watching the sunset by a lighthouse',
    emotionalTone: 'calm',
    keywords: ['ocean', 'lighthouse', 'cliff', 'sunset', 'sailboat'],
    ambience: ['ocean'],
    focal: { x: 0.3, y: 0.6 },
  },
  {
    id: 'duo-underwater-turtle-01',
    src: '/images/scenes/duo-underwater-turtle-01.jpg',
    width: 345,
    height: 298,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_03 AM.png',
    sourcePanel: 'r1c3',
    theme: ['underwater', 'ocean'],
    environment: 'underwater',
    indoor: false,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: false,
    characters: 'boy-girl',
    characterCount: 2,
    dogPresent: false,
    otherAnimals: ['turtle', 'fish'],
    transportation: [],
    activity: 'swimming underwater together with a sea turtle',
    emotionalTone: 'wonder',
    keywords: ['underwater', 'ocean', 'turtle', 'coral', 'swimming'],
    ambience: ['ocean'],
    focal: { x: 0.4, y: 0.6 },
  },
  {
    id: 'trio-hotairballoon-valley-01',
    src: '/images/scenes/trio-hotairballoon-valley-01.jpg',
    width: 347,
    height: 298,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_03 AM.png',
    sourcePanel: 'r1c4',
    theme: ['hot air balloon', 'valley'],
    environment: 'sky',
    indoor: false,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: false,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: [],
    transportation: ['hot-air-balloon'],
    activity: 'riding in a hot air balloon over a green valley',
    emotionalTone: 'adventurous',
    keywords: ['hot air balloon', 'valley', 'river', 'flying', 'sky'],
    ambience: ['countryside', 'fantasy'],
    focal: { x: 0.35, y: 0.55 },
  },
  {
    id: 'trio-fantasy-city-night-moon-01',
    src: '/images/scenes/trio-fantasy-city-night-moon-01.jpg',
    width: 344,
    height: 267,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_03 AM.png',
    sourcePanel: 'r2c1',
    theme: ['fantasy city', 'night'],
    environment: 'fantasy',
    indoor: false,
    timeOfDay: 'night',
    weatherSeason: null,
    fantasy: true,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: [],
    transportation: [],
    activity: 'sitting on a rooftop looking over a fantasy city at night',
    emotionalTone: 'wonder',
    keywords: ['fantasy city', 'night', 'moon', 'rooftop', 'lights'],
    ambience: ['fantasy'],
    focal: { x: 0.3, y: 0.6 },
  },
  {
    id: 'trio-jungle-temple-waterfall-01',
    src: '/images/scenes/trio-jungle-temple-waterfall-01.jpg',
    width: 345,
    height: 267,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_03 AM.png',
    sourcePanel: 'r2c2',
    theme: ['jungle', 'ancient temple'],
    environment: 'jungle',
    indoor: false,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: false,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: [],
    transportation: [],
    activity: 'standing at the entrance of a jungle temple by a waterfall',
    emotionalTone: 'adventurous',
    keywords: ['jungle', 'temple', 'ruins', 'waterfall', 'explorer'],
    ambience: ['jungle'],
    focal: { x: 0.4, y: 0.6 },
  },
  {
    id: 'trio-snow-sled-village-sunset-01',
    src: '/images/scenes/trio-snow-sled-village-sunset-01.jpg',
    width: 345,
    height: 267,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_03 AM.png',
    sourcePanel: 'r2c3',
    theme: ['snow', 'sledding'],
    environment: 'snow',
    indoor: false,
    timeOfDay: 'dusk',
    weatherSeason: 'snow',
    fantasy: false,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: [],
    transportation: ['sled'],
    activity: 'sledding down a snowy hill toward the village at sunset',
    emotionalTone: 'joyful',
    keywords: ['snow', 'sled', 'sledding', 'village', 'winter'],
    ambience: ['countryside', 'fantasy'],
    focal: { x: 0.35, y: 0.55 },
  },
  {
    id: 'trio-desert-ruins-camels-sunset-01',
    src: '/images/scenes/trio-desert-ruins-camels-sunset-01.jpg',
    width: 347,
    height: 267,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_03 AM.png',
    sourcePanel: 'r2c4',
    theme: ['desert', 'ancient ruins'],
    environment: 'desert',
    indoor: false,
    timeOfDay: 'dusk',
    weatherSeason: null,
    fantasy: false,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: ['camels'],
    transportation: [],
    activity: 'exploring desert ruins with camels passing by at sunset',
    emotionalTone: 'adventurous',
    keywords: ['desert', 'ruins', 'camels', 'sunset', 'pyramid'],
    ambience: ['countryside'],
    focal: { x: 0.35, y: 0.6 },
  },
  {
    id: 'trio-fantasy-castle-valley-overlook-01',
    src: '/images/scenes/trio-fantasy-castle-valley-overlook-01.jpg',
    width: 344,
    height: 265,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_03 AM.png',
    sourcePanel: 'r3c1',
    theme: ['fantasy castle', 'valley'],
    environment: 'fantasy',
    indoor: false,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: true,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: [],
    transportation: [],
    activity: 'overlooking a fairytale castle in a green valley',
    emotionalTone: 'wonder',
    keywords: ['castle', 'fantasy', 'valley', 'waterfall', 'overlook'],
    ambience: ['fantasy'],
    focal: { x: 0.3, y: 0.6 },
  },
  {
    id: 'trio-dinosaur-valley-01',
    src: '/images/scenes/trio-dinosaur-valley-01.jpg',
    width: 345,
    height: 265,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_03 AM.png',
    sourcePanel: 'r3c2',
    theme: ['dinosaurs', 'valley'],
    environment: 'jungle',
    indoor: false,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: true,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: ['dinosaur'],
    transportation: [],
    activity: 'meeting a friendly dinosaur in a green valley',
    emotionalTone: 'wonder',
    keywords: ['dinosaur', 'valley', 'forest', 'prehistoric'],
    ambience: ['jungle', 'fantasy'],
    focal: { x: 0.4, y: 0.6 },
  },
  {
    id: 'trio-astronaut-rocket-launch-night-01',
    src: '/images/scenes/trio-astronaut-rocket-launch-night-01.jpg',
    width: 345,
    height: 265,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_03 AM.png',
    sourcePanel: 'r3c3',
    theme: ['space', 'rocket launch'],
    environment: 'space',
    indoor: false,
    timeOfDay: 'night',
    weatherSeason: null,
    fantasy: false,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: [],
    transportation: ['rocket'],
    activity: 'watching a rocket launch into space at night',
    emotionalTone: 'adventurous',
    keywords: ['space', 'rocket', 'astronaut', 'launch', 'night', 'moon'],
    ambience: ['space'],
    focal: { x: 0.3, y: 0.6 },
  },
  {
    id: 'trio-treehouse-valley-overlook-01',
    src: '/images/scenes/trio-treehouse-valley-overlook-01.jpg',
    width: 347,
    height: 265,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_03 AM.png',
    sourcePanel: 'r3c4',
    theme: ['treehouse', 'valley'],
    environment: 'forest',
    indoor: true,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: false,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: [],
    transportation: [],
    activity: 'sitting in a treehouse overlooking a green valley',
    emotionalTone: 'calm',
    keywords: ['treehouse', 'valley', 'forest', 'overlook', 'river'],
    ambience: ['countryside', 'jungle'],
    focal: { x: 0.3, y: 0.6 },
  },
  {
    id: 'trio-village-flowers-street-01',
    src: '/images/scenes/trio-village-flowers-street-01.jpg',
    width: 344,
    height: 257,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_03 AM.png',
    sourcePanel: 'r4c1',
    theme: ['village', 'flowers'],
    environment: 'urban',
    indoor: false,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: false,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: [],
    transportation: [],
    activity: 'walking down a flower-covered village street',
    emotionalTone: 'joyful',
    keywords: ['village', 'street', 'flowers', 'town', 'cobblestone'],
    ambience: ['countryside', 'fantasy'],
    focal: { x: 0.35, y: 0.6 },
  },
  {
    id: 'trio-pirate-ship-night-dock-01',
    src: '/images/scenes/trio-pirate-ship-night-dock-01.jpg',
    width: 345,
    height: 257,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_03 AM.png',
    sourcePanel: 'r4c2',
    theme: ['ocean', 'pirate ship'],
    environment: 'ocean',
    indoor: false,
    timeOfDay: 'night',
    weatherSeason: null,
    fantasy: true,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: [],
    transportation: ['ship'],
    activity: 'watching a pirate ship sail by at night from the dock',
    emotionalTone: 'adventurous',
    keywords: ['ocean', 'pirate ship', 'night', 'moon', 'dock', 'lantern'],
    ambience: ['ocean', 'fantasy'],
    focal: { x: 0.35, y: 0.6 },
  },
  {
    id: 'trio-meadow-rainbow-01',
    src: '/images/scenes/trio-meadow-rainbow-01.jpg',
    width: 345,
    height: 257,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_03 AM.png',
    sourcePanel: 'r4c3',
    theme: ['meadow', 'rainbow'],
    environment: 'meadow',
    indoor: false,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: false,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: [],
    transportation: [],
    activity: 'sitting together in a flower meadow under a rainbow',
    emotionalTone: 'joyful',
    keywords: ['meadow', 'rainbow', 'flowers', 'field'],
    ambience: ['countryside', 'fantasy'],
    focal: { x: 0.35, y: 0.6 },
  },
  {
    id: 'trio-tent-storytime-night-01',
    src: '/images/scenes/trio-tent-storytime-night-01.jpg',
    width: 347,
    height: 257,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_03 AM.png',
    sourcePanel: 'r4c4',
    theme: ['camping', 'storytime'],
    environment: 'indoor-home',
    indoor: true,
    timeOfDay: 'night',
    weatherSeason: null,
    fantasy: false,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: [],
    transportation: [],
    activity: 'reading a story together inside a cozy blanket tent at night',
    emotionalTone: 'cozy',
    keywords: ['tent', 'storytime', 'reading', 'night', 'fairy lights', 'cozy'],
    ambience: [],
    focal: { x: 0.4, y: 0.6 },
  },
  {
    id: 'trio-mountain-valley-sunset-hill-01',
    src: '/images/scenes/trio-mountain-valley-sunset-hill-01.jpg',
    width: 468,
    height: 360,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_12 AM.png',
    sourcePanel: 'r1c1',
    theme: ['mountains', 'valley'],
    environment: 'mountain',
    indoor: false,
    timeOfDay: 'dusk',
    weatherSeason: null,
    fantasy: false,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: [],
    transportation: [],
    activity: 'sitting on a grassy hill watching the sunset over the mountains',
    emotionalTone: 'calm',
    keywords: ['mountain', 'valley', 'hill', 'sunset', 'river'],
    ambience: ['countryside', 'fantasy'],
    focal: { x: 0.25, y: 0.6 },
  },
  {
    id: 'trio-rowboat-castle-lake-01',
    src: '/images/scenes/trio-rowboat-castle-lake-01.jpg',
    width: 471,
    height: 360,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_12 AM.png',
    sourcePanel: 'r1c2',
    theme: ['lake', 'fantasy castle'],
    environment: 'fantasy',
    indoor: false,
    timeOfDay: 'dusk',
    weatherSeason: null,
    fantasy: true,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: [],
    transportation: ['rowboat'],
    activity: 'rowing a boat across a lake toward a fairytale castle',
    emotionalTone: 'wonder',
    keywords: ['lake', 'rowboat', 'castle', 'fantasy', 'sunset'],
    ambience: ['fantasy', 'ocean'],
    focal: { x: 0.4, y: 0.55 },
  },
  {
    id: 'trio-camping-campfire-night-01',
    src: '/images/scenes/trio-camping-campfire-night-01.jpg',
    width: 481,
    height: 360,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_12 AM.png',
    sourcePanel: 'r1c3',
    theme: ['camping', 'stars'],
    environment: 'forest',
    indoor: false,
    timeOfDay: 'night',
    weatherSeason: null,
    fantasy: false,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: [],
    transportation: [],
    activity: 'sitting by a campfire under a starry sky',
    emotionalTone: 'cozy',
    keywords: ['camping', 'campfire', 'stars', 'tent', 'night', 'shooting star'],
    ambience: ['space', 'countryside'],
    focal: { x: 0.3, y: 0.6 },
  },
  {
    id: 'trio-pyramids-sphinx-desert-01',
    src: '/images/scenes/trio-pyramids-sphinx-desert-01.jpg',
    width: 468,
    height: 347,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_12 AM.png',
    sourcePanel: 'r2c1',
    theme: ['desert', 'pyramids'],
    environment: 'desert',
    indoor: false,
    timeOfDay: 'dusk',
    weatherSeason: null,
    fantasy: false,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: [],
    transportation: [],
    activity: 'exploring the desert near the pyramids and sphinx',
    emotionalTone: 'adventurous',
    keywords: ['desert', 'pyramids', 'sphinx', 'egypt', 'sand'],
    ambience: ['countryside'],
    focal: { x: 0.3, y: 0.6 },
  },
  {
    id: 'trio-treehouse-waterfall-bridge-01',
    src: '/images/scenes/trio-treehouse-waterfall-bridge-01.jpg',
    width: 471,
    height: 347,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_12 AM.png',
    sourcePanel: 'r2c2',
    theme: ['forest', 'treehouse'],
    environment: 'forest',
    indoor: true,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: false,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: [],
    transportation: [],
    activity: 'sitting on a stone bridge by a waterfall near a treehouse',
    emotionalTone: 'calm',
    keywords: ['forest', 'waterfall', 'bridge', 'treehouse', 'stream'],
    ambience: ['jungle', 'countryside'],
    focal: { x: 0.4, y: 0.6 },
  },
  {
    id: 'trio-ocean-cliff-lighthouse-sunset-01',
    src: '/images/scenes/trio-ocean-cliff-lighthouse-sunset-01.jpg',
    width: 481,
    height: 347,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_12 AM.png',
    sourcePanel: 'r2c3',
    theme: ['ocean', 'lighthouse'],
    environment: 'ocean',
    indoor: false,
    timeOfDay: 'dusk',
    weatherSeason: null,
    fantasy: false,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: [],
    transportation: [],
    activity: 'sitting on a cliff by the ocean watching the sunset near a lighthouse',
    emotionalTone: 'calm',
    keywords: ['ocean', 'cliff', 'lighthouse', 'sunset', 'waves'],
    ambience: ['ocean'],
    focal: { x: 0.3, y: 0.6 },
  },
  {
    id: 'trio-mushroom-forest-dusk-01',
    src: '/images/scenes/trio-mushroom-forest-dusk-01.jpg',
    width: 468,
    height: 354,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_12 AM.png',
    sourcePanel: 'r3c1',
    theme: ['enchanted forest', 'glowing mushrooms'],
    environment: 'fantasy',
    indoor: false,
    timeOfDay: 'dusk',
    weatherSeason: null,
    fantasy: true,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: [],
    transportation: [],
    activity: 'walking through an enchanted forest of glowing mushrooms',
    emotionalTone: 'wonder',
    keywords: ['enchanted forest', 'mushrooms', 'glow', 'fairy lights', 'magic'],
    ambience: ['fantasy'],
    focal: { x: 0.35, y: 0.6 },
  },
  {
    id: 'trio-rainbow-waterfall-bridge-01',
    src: '/images/scenes/trio-rainbow-waterfall-bridge-01.jpg',
    width: 471,
    height: 354,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_12 AM.png',
    sourcePanel: 'r3c2',
    theme: ['forest', 'waterfall', 'rainbow'],
    environment: 'forest',
    indoor: false,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: false,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: [],
    transportation: [],
    activity: 'crossing a rope bridge toward a waterfall and rainbow',
    emotionalTone: 'wonder',
    keywords: ['waterfall', 'rainbow', 'rope bridge', 'forest', 'stream'],
    ambience: ['jungle', 'countryside'],
    focal: { x: 0.4, y: 0.6 },
  },
  {
    id: 'trio-train-snow-aurora-night-01',
    src: '/images/scenes/trio-train-snow-aurora-night-01.jpg',
    width: 481,
    height: 354,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_12 AM.png',
    sourcePanel: 'r3c3',
    theme: ['snow', 'train', 'aurora'],
    environment: 'snow',
    indoor: false,
    timeOfDay: 'night',
    weatherSeason: 'snow',
    fantasy: false,
    characters: 'trio',
    characterCount: 3,
    dogPresent: true,
    otherAnimals: [],
    transportation: ['train'],
    activity: 'watching a steam train arrive under the northern lights',
    emotionalTone: 'wonder',
    keywords: ['snow', 'train', 'aurora', 'northern lights', 'village', 'winter'],
    ambience: ['countryside', 'space'],
    focal: { x: 0.3, y: 0.6 },
  },
  {
    id: 'pair-girl-dog-beach-lighthouse-sunset-01',
    src: '/images/scenes/pair-girl-dog-beach-lighthouse-sunset-01.jpg',
    width: 715,
    height: 535,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_19 AM.png',
    sourcePanel: 'r1c1',
    theme: ['ocean', 'lighthouse'],
    environment: 'beach',
    indoor: false,
    timeOfDay: 'dusk',
    weatherSeason: null,
    fantasy: false,
    characters: 'pair-girl-dog',
    characterCount: 2,
    dogPresent: true,
    otherAnimals: [],
    transportation: [],
    activity: 'sitting on the beach with her dog watching the sunset by a lighthouse',
    emotionalTone: 'calm',
    keywords: ['ocean', 'beach', 'lighthouse', 'sunset', 'dog'],
    ambience: ['ocean'],
    focal: { x: 0.3, y: 0.6 },
  },
  {
    id: 'pair-girl-dog-treehouse-reading-nook-01',
    src: '/images/scenes/pair-girl-dog-treehouse-reading-nook-01.jpg',
    width: 718,
    height: 535,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_19 AM.png',
    sourcePanel: 'r1c2',
    theme: ['treehouse', 'reading nook'],
    environment: 'forest',
    indoor: true,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: false,
    characters: 'pair-girl-dog',
    characterCount: 2,
    dogPresent: true,
    otherAnimals: [],
    transportation: [],
    activity: 'reading with her dog in a cozy treehouse nook',
    emotionalTone: 'cozy',
    keywords: ['treehouse', 'reading', 'books', 'forest', 'dog', 'cozy'],
    ambience: ['countryside', 'jungle'],
    focal: { x: 0.35, y: 0.55 },
  },
  {
    id: 'pair-girl-dog-temple-ruins-desert-map-01',
    src: '/images/scenes/pair-girl-dog-temple-ruins-desert-map-01.jpg',
    width: 715,
    height: 535,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_19 AM.png',
    sourcePanel: 'r2c1',
    theme: ['desert', 'ancient ruins'],
    environment: 'desert',
    indoor: false,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: false,
    characters: 'pair-girl-dog',
    characterCount: 2,
    dogPresent: true,
    otherAnimals: [],
    transportation: [],
    activity: 'exploring desert ruins with a map and her dog',
    emotionalTone: 'adventurous',
    keywords: ['desert', 'ruins', 'temple', 'explorer', 'map', 'dog'],
    ambience: ['countryside'],
    focal: { x: 0.4, y: 0.6 },
  },
  {
    id: 'pair-girl-dog-hotairballoon-floating-castle-01',
    src: '/images/scenes/pair-girl-dog-hotairballoon-floating-castle-01.jpg',
    width: 718,
    height: 535,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_19 AM.png',
    sourcePanel: 'r2c2',
    theme: ['hot air balloon', 'floating castle'],
    environment: 'fantasy',
    indoor: false,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: true,
    characters: 'pair-girl-dog',
    characterCount: 2,
    dogPresent: true,
    otherAnimals: [],
    transportation: ['hot-air-balloon'],
    activity: 'floating in a hot air balloon toward a floating fantasy castle with her dog',
    emotionalTone: 'wonder',
    keywords: ['hot air balloon', 'floating castle', 'fantasy', 'sky', 'dog'],
    ambience: ['fantasy'],
    focal: { x: 0.3, y: 0.55 },
  },
  {
    id: 'pair-boy-dog-river-valley-sunset-01',
    src: '/images/scenes/pair-boy-dog-river-valley-sunset-01.jpg',
    width: 715,
    height: 534,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_28 AM.png',
    sourcePanel: 'r1c1',
    theme: ['river', 'valley'],
    environment: 'countryside',
    indoor: false,
    timeOfDay: 'dusk',
    weatherSeason: null,
    fantasy: false,
    characters: 'pair-boy-dog',
    characterCount: 2,
    dogPresent: true,
    otherAnimals: [],
    transportation: [],
    activity: 'sitting under a tree with his dog watching the sunset over the valley',
    emotionalTone: 'calm',
    keywords: ['river', 'valley', 'sunset', 'tree', 'dog', 'countryside'],
    ambience: ['countryside', 'farm'],
    focal: { x: 0.3, y: 0.6 },
  },
  {
    id: 'pair-boy-dog-lighthouse-ocean-night-01',
    src: '/images/scenes/pair-boy-dog-lighthouse-ocean-night-01.jpg',
    width: 715,
    height: 534,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_28 AM.png',
    sourcePanel: 'r1c2',
    theme: ['ocean', 'lighthouse'],
    environment: 'ocean',
    indoor: false,
    timeOfDay: 'night',
    weatherSeason: null,
    fantasy: false,
    characters: 'pair-boy-dog',
    characterCount: 2,
    dogPresent: true,
    otherAnimals: [],
    transportation: [],
    activity: 'sitting on rocks with his dog watching the moonlit ocean by a lighthouse',
    emotionalTone: 'calm',
    keywords: ['ocean', 'lighthouse', 'night', 'moon', 'dog'],
    ambience: ['ocean'],
    focal: { x: 0.3, y: 0.55 },
  },
  {
    id: 'pair-boy-dog-forest-fireflies-treehouse-door-01',
    src: '/images/scenes/pair-boy-dog-forest-fireflies-treehouse-door-01.jpg',
    width: 715,
    height: 536,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_28 AM.png',
    sourcePanel: 'r2c1',
    theme: ['forest', 'fireflies'],
    environment: 'forest',
    indoor: false,
    timeOfDay: 'dusk',
    weatherSeason: null,
    fantasy: true,
    characters: 'pair-boy-dog',
    characterCount: 2,
    dogPresent: true,
    otherAnimals: [],
    transportation: [],
    activity: 'walking with his dog past magical fireflies toward a glowing treehouse door',
    emotionalTone: 'wonder',
    keywords: ['forest', 'fireflies', 'magic', 'treehouse', 'dog', 'path'],
    ambience: ['fantasy', 'jungle'],
    focal: { x: 0.4, y: 0.6 },
  },
  {
    id: 'pair-boy-dog-sled-snow-village-sunset-01',
    src: '/images/scenes/pair-boy-dog-sled-snow-village-sunset-01.jpg',
    width: 715,
    height: 536,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_28 AM.png',
    sourcePanel: 'r2c2',
    theme: ['snow', 'sledding'],
    environment: 'snow',
    indoor: false,
    timeOfDay: 'dusk',
    weatherSeason: 'snow',
    fantasy: false,
    characters: 'pair-boy-dog',
    characterCount: 2,
    dogPresent: true,
    otherAnimals: [],
    transportation: ['sled'],
    activity: 'sledding down a snowy hill with his dog toward the village at sunset',
    emotionalTone: 'joyful',
    keywords: ['snow', 'sled', 'sledding', 'village', 'dog', 'winter'],
    ambience: ['countryside', 'fantasy'],
    focal: { x: 0.35, y: 0.6 },
  },
  {
    id: 'bg-river-valley-sunset-01',
    src: '/images/scenes/bg-river-valley-sunset-01.jpg',
    width: 708,
    height: 529,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_38 AM.png',
    sourcePanel: 'r1c1',
    theme: ['river', 'valley'],
    environment: 'countryside',
    indoor: false,
    timeOfDay: 'dusk',
    weatherSeason: null,
    fantasy: false,
    characters: 'none',
    characterCount: 0,
    dogPresent: false,
    otherAnimals: [],
    transportation: [],
    activity: 'a quiet valley with a winding river at sunset',
    emotionalTone: 'calm',
    keywords: ['river', 'valley', 'sunset', 'mountains', 'meadow'],
    ambience: ['countryside', 'farm'],
    focal: { x: 0.5, y: 0.5 },
  },
  {
    id: 'bg-meadow-path-sunny-01',
    src: '/images/scenes/bg-meadow-path-sunny-01.jpg',
    width: 709,
    height: 529,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_38 AM.png',
    sourcePanel: 'r1c2',
    theme: ['meadow', 'path'],
    environment: 'meadow',
    indoor: false,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: false,
    characters: 'none',
    characterCount: 0,
    dogPresent: false,
    otherAnimals: [],
    transportation: [],
    activity: 'a sunny meadow path through rolling green hills',
    emotionalTone: 'peaceful',
    keywords: ['meadow', 'path', 'hills', 'sunny', 'countryside'],
    ambience: ['countryside', 'farm'],
    focal: { x: 0.5, y: 0.5 },
  },
  {
    id: 'bg-coastal-cliff-sunset-01',
    src: '/images/scenes/bg-coastal-cliff-sunset-01.jpg',
    width: 708,
    height: 529,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_38 AM.png',
    sourcePanel: 'r2c1',
    theme: ['ocean', 'coast'],
    environment: 'ocean',
    indoor: false,
    timeOfDay: 'dusk',
    weatherSeason: null,
    fantasy: false,
    characters: 'none',
    characterCount: 0,
    dogPresent: false,
    otherAnimals: [],
    transportation: [],
    activity: 'a quiet coastal cliff overlooking the ocean at sunset',
    emotionalTone: 'calm',
    keywords: ['ocean', 'cliff', 'coast', 'sunset', 'waves'],
    ambience: ['ocean'],
    focal: { x: 0.5, y: 0.55 },
  },
  {
    id: 'bg-forest-bridge-stream-01',
    src: '/images/scenes/bg-forest-bridge-stream-01.jpg',
    width: 709,
    height: 529,
    sourceFile: 'ChatGPT Image Aug 20, 2026 at 11_25_38 AM.png',
    sourcePanel: 'r2c2',
    theme: ['forest', 'stream'],
    environment: 'forest',
    indoor: false,
    timeOfDay: 'day',
    weatherSeason: null,
    fantasy: false,
    characters: 'none',
    characterCount: 0,
    dogPresent: false,
    otherAnimals: [],
    transportation: [],
    activity: 'a sunlit forest path crossing a stream by a stone bridge',
    emotionalTone: 'peaceful',
    keywords: ['forest', 'stream', 'bridge', 'path', 'flowers'],
    ambience: ['countryside', 'jungle', 'fantasy'],
    focal: { x: 0.4, y: 0.55 },
  },
];

/** Wave 1 visual gate. Only reviewed, character-neutral storybook
 * environments may enter runtime selection. Every other historical scene is
 * quarantined by omission until a human explicitly approves it. */
export const APPROVED_SCENE_IDS = [
  'bg-river-valley-sunset-01',
  'bg-meadow-path-sunny-01',
  'bg-coastal-cliff-sunset-01',
  'bg-forest-bridge-stream-01',
] as const;

const approvedIds = new Set<string>(APPROVED_SCENE_IDS);
export const RUNTIME_SCENE_MANIFEST = SCENE_MANIFEST.filter((asset) => approvedIds.has(asset.id));

export function sceneApproval(assetId: string): 'approved' | 'quarantined' {
  return approvedIds.has(assetId) ? 'approved' : 'quarantined';
}
